"""empty message

Revision ID: 8369644cc3ba
Revises: 53a36e55fed6
Create Date: 2019-02-27 16:23:28.552443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8369644cc3ba'
down_revision = '53a36e55fed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
